language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.1
branches:
  only:
    - master
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("WaterFlows")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
notifications:
  email: false
